### ISSUE TITLE
Container command not found or does not exist

### ISSUE THREAD

**Issue by paolocarrasco** [pascalgrimaud/docker-jboss-as#1]
Hi,
I found this repo interesting for my needs, but sadly it's not working when I run the command

``` console
$ docker run -d -p 8080:8080 -p 9990:9990 pascalgrimaud/jboss-as:7.1.1
```

Even though I did the build step, I received the following error that is not helping me to understand the problem:

![docker jboss not working](https://cloud.githubusercontent.com/assets/1524522/13795987/2bf24610-ead2-11e5-8887-45f3b47d6ee7.png)

Do you happen to know what would be the problem with it?

Thanks in advance

**Comment by pascalgrimaud** [comment]
Hello!
Try this command instead: `docker run -d -p 8080:8080 -p 9990:9990 pascalgrimaud/jboss-as`
In [docker hub tag](https://hub.docker.com/r/pascalgrimaud/jboss-as/tags/), I forget to tag 7.1.1 => the README is not correct

**Comment by paolocarrasco** [comment]
Thanks! It worked :)
